name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check Runner
        run: echo "Running on a self-hosted runner!"

